### ISSUE TITLE
Application Instantiation Error 

### ISSUE THREAD

**Issue by ralrom** [joomla/docker-joomla#12]
Hello I am getting an error about the session table not existing:
 ```
Error displaying the error page: Application Instantiation Error: Table 'joomla.#__session' doesn't exist SQL=SELECT `session_id` FROM `#__session` WHERE `session_id` = 'dbd707b3cb7562218a6d6db8b2b1befb' LIMIT 1
```

Here is my docker-compose.yml
```
version: '2'
services:
  joomla:
    image: joomla
    links:
      - joomladb:mysql
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      MYSQL_PORT_3306_TCP: 3306
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: "example"
      JOOMLA_DB_USER: "root"
      JOOMLA_DB_NAME: "joomla"
  joomladb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "joomla"
```
