### ISSUE TITLE
Works with Joomla 2.5.x ?

### ISSUE THREAD

**Issue by dotMastaz** [joomla/docker-joomla#20]
Hello,

Thanks for work !!
And i work with Joomla 2.5.x ?
That's work again ?

Thank you !

**Comment by mbabker** [comment]
Docker images are only being created and maintained for supported Joomla versions, right now that's 3.6 only.  There is no plan to create images for older Joomla versions, though you are free to take the PHP 5.6 Dockerfile and adjust it to work with 2.5 (all it should require is changing the download URL to use 2.5.28 versus 3.6.5).

**Comment by moble** [comment]
I can verify that the approach @mbabker suggested does work (I also had to change `JOOMLA_SHA1` to match whatever gets downloaded).  Even better, if you already have your web root all set up, you can just use the image without any changes.  For example, here's my `docker-compose.yml` file:

```yaml
version: '3'

services:
  joomladb:
    image: mysql
    volumes:
      - ./joomladb:/var/lib/mysql

  joomla:
    image: joomla
    command: bash -c "echo 'ServerName www.my-server.com' >> /etc/apache2/apache2.conf && apache2-foreground"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: joomla_db_user
      JOOMLA_DB_PASSWORD: "MY_PASSWORD"
    depends_on:
      - joomladb
    volumes:
      - ./joomla:/var/www/html

```

Note that my local directories `./joomladb` and `./joomla` already exist and have everything they need in them.

For added security with version 2.5 (can't upgrade...), I've also made my public site read-only, so I give it a mysql user with minimal permissions (read anything in my joomla db; write only in `_categories`, `_content`, and `_session` tables), and I mount the joomla directory read-only except for the `cache` subdirectory.  But then I can start another docker with a read-write version if I need to change things.
