### ISSUE TITLE
Can't install - infinite loop

### ISSUE THREAD

**Issue by Cafeinoman** [joomla/docker-joomla#28]
When I try to install joomla with docker compose, I get a strange on the last screen.
Installation is done on an up to date archlinux, with latest docker-ce installation. 
The docker-compose file :

```yaml
version: '3.1'

services:
    joomla:
        image: joomla
        links:
            - joomladb:mysql
        ports:
            - 8080:80
        environment:
          MYSQL_PORT_3306_TCP: 3306
          JOOMLA_DB_HOST: joomladb
          JOOMLA_DB_USER: joomla
          JOOMLA_DB_PASSWORD: joomla
        volumes:
            - /home/francois/PCF/site_valenton/www:/var/www/html
    joomladb:
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: joomla
            MYSQL_DATABASE: joomla
            MYSQL_USER: joomla
            MYSQL_PASSWORD: joomla
        volumes:
            - /home/francois/PCF/site_valenton/db:/var/lib/mysql
```

And this 2 request are infinitly repeated when installation is launched.

```sh
joomla_1    | 172.18.0.1 - - [14/Aug/2017:18:35:52 +0000] "POST /installation/index.php HTTP/1.1" 200 388 "http://localhost:8080/installation/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
joomla_1    | 172.18.0.1 - - [14/Aug/2017:18:35:52 +0000] "GET /installation/index.php?tmpl=body&view=database HTTP/1.1" 200 2052 "http://localhost:8080/installation/index.php" "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
```
There's no logged problem with the connection between the 2 containers.
