### ISSUE TITLE
The installation freezes and do not finish

### ISSUE THREAD

**Issue by andergmartins** [joomla/docker-joomla#29]
Can't start new containers anymore. The installation freezes. 

![127 0 0 1-32780-installation-index php](https://user-images.githubusercontent.com/407131/29385577-97da9bb4-82ae-11e7-9b6a-79419c73af5f.png)

I have tried on the tags: latest and 3.7.3-apache-php7
Tried locally and in the PWD.

Here is my docker-compose file:

```
version: '3.1'

services:
    joomla:
        image: joomla:3.7.3-apache-php7
        links:
            - joomladb:mysql
        ports:
            - 80
        environment:
          JOOMLA_DB_HOST: joomladb
          JOOMLA_DB_PASSWORD: root
        volumes:
            - /home/anderson/Volumes/joomla-php7/www:/var/www/html:z

    joomladb:
        image: mysql:5.6
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /home/anderson/Volumes/joomla-php7/db:/var/lib/mysql:z
```

And I'm sure I have removed the temporary file created in the installation directory to verify the ownership but one of the warning keeps showing.
