### ISSUE TITLE
adapt docker-entrypoint.sh to joomla v3.8.x

### ISSUE THREAD

**Issue by eberttim** [joomla/docker-joomla#35]
I am running the Joomla image as a service on a docker stack.
In order to keep my installation across different Joomla containers I mounted the `/var/www/html` directory to the service.

But when I remove the docker stack and deploy it again with the same configuration, the `docker-entrypoint.sh` script copies the installation directory again even though there is a current version installed.

This means the configuration of the existing Joomla installation is kept but it will result in a prompt to remove the installation directory when visiting the website.

example `docker-compose.yml`:
```yml
version: '3.1'

services:
  joomla:
    image: joomla:latest
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "./data:/var/www/html"
# and so on...
```

I think the problem here is, that the `docker-entrypoint.sh` checks for existance of **`libraries/cms/version/version.php`** in the following line even though 
in Joomla version 3.8.0 and up, the version file is located under **`libraries/src/Version.php`**:

```sh
if ! [ -e index.php -a -e libraries/cms/version/version.php ]; then
```

See: https://docs.joomla.org/How_to_check_the_Joomla_version%3F#Other_Ways_6
