### ISSUE TITLE
cannot install joomla using docker

### ISSUE THREAD

**Issue by xhallix** [joomla/docker-joomla#7]
#### Steps to reproduce the issue

https://hub.docker.com/_/joomla/
Follow the instructions
Use docker-compose up -d 
#### Expected result

Installation works
#### Actual result

Install step 2 breaks because `throw new RuntimeException('Could not connect to MySQL');`in `driver/msqli.php` 
#### System information (as much as possible)

Ubuntu 14.04 lts
#### Additional comments

MysqlContainer is running and I can connect with root | example by exec into the docker container or using a query browser like mysqlworkbench

I think it is an issue with container interaction, because they dont seem to reach each other

**Comment by xhallix** [comment]
I did some changes to the docker-compose file to ensure the containers will connect correctly to each other. Not sure if thiis is the correct way, but it works.

*docker version*
```
Docker version 1.11.2, build b9f10c9
 ```

*docker compose version*
```
docker-compose version 1.6.2, build 4d72027
```

```` 
version: '2'
services:
  joomla:
    image: joomla
    links:
      - joomladb:mysql
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    environment:
      MYSQL_PORT_3306_TCP: 3306
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: "example"
      JOOMLA_DB_USER: "root"
      JOOMLA_DB_NAME: "joomla"        

  joomladb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "joomla"
```                            
         
during the installation use `joomladb` instead of localhost
