### ISSUE TITLE
Cannot access MEDIA due to Load denied by X-Frame-Options: “DENY” error

### ISSUE THREAD

**Issue by dpicts** [joomla/docker-joomla#82]
Launch with docker-compose.yaml below, then complete the install... when I go to Admin section and click on Media, I am shown a blank page and the console shows the following error: 
`Load denied by X-Frame-Options: “DENY” from “https://test.mydomain.com/administrator/index.php?option=com_media&view=mediaList&tmpl=component&folder=”, site does not permit any framing. Attempted to load into “https://test.mydomain.com/administrator/index.php?option=com_media”.`

```yaml
version: '3.7'

services:
  #Database
  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - backend
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla

  #Joomla
  joomlasite:
    depends_on:
      - db
    image: joomla:latest
    restart: always
    networks:
      - frontend
      - backend
    volumes:
      - ./html:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.middlewares.joomlasite-ssl.redirectscheme.scheme=https"
      - "traefik.http.routers.joomlasite-http.entrypoints=web"
      - "traefik.http.routers.joomlasite-http.rule=Host(`test.mydomain.com`)"
      - "traefik.http.routers.joomlasite-http.middlewares=joomlasite-ssl@docker"

      - "traefik.http.routers.joomlasite.middlewares=secureHeader@file"
      - "traefik.http.routers.joomlasite.entrypoints=websecure"
      - "traefik.http.routers.joomlasite.rule=Host(`test.mydomain.com`)"

      - "traefik.http.routers.joomlasite.tls=true"
      - "traefik.http.routers.joomlasite.tls.certresolver=le-tls"


    environment:
      JOOMLA_DB_HOST: db:3306
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla

networks:
  backend:
  frontend:
    external:
      name: traefik-proxy
```
